version: "3"

services: 
  app:
    build: 
      context: .
    ports: 
      - "8000:8000"
    env_file:
      - api_env.list
      - db_env.list # contains db name and user variables
    volumes: 
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - db_env.list
